name: Build Test

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build check
        if: always()
        run: npm run build

      - name: Run Danger
        if: always()
        run: npx danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
